steps:
  # Step 1: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/divine-course-470809-f6/student-form-repo/student-form-app:$COMMIT_SHA',
        '.'
      ]
    waitFor: ["-"]

  # Step 2: Push Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/divine-course-470809-f6/student-form-repo/student-form-app:$COMMIT_SHA'
      ]
    waitFor: ["Build"]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'student-form-app',
        '--image', 'us-central1-docker.pkg.dev/divine-course-470809-f6/student-form-repo/student-form-app:$COMMIT_SHA',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]
    waitFor: ["Push"]

images:
  - 'us-central1-docker.pkg.dev/divine-course-470809-f6/student-form-repo/student-form-app:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/divine-course-470809-f6/student-form-repo/student-form-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
